spring:
  main:
      banner-mode: log
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/cpdaily
    username : root
    password : 123456
    type : com.alibaba.druid.pool.DruidDataSource
    driver-class-name : com.mysql.jdbc.Driver
    filters : stat
    maxActive : 20
    initialSize : 1
    maxWait : 60000
    minIdle : 1
    timeBetweenEvictionRunsMillis : 60000
    minEvictableIdleTimeMillis : 300000
    validationQuery : select 'x'
    testWhileIdle : true
    testOnBorrow : false
    testOnReturn : false
    poolPreparedStatements : true
    maxOpenPreparedStatements : 20

  redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password: 123456
      pool:
        min-idle: 0    # 连接池中的最小空闲连接
        max-idle: 8    # 连接池中的最大空闲连接
        max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制)
        max-active: 8  # 最大连接数
      timeout: 2000    # 连接超时时间（毫秒）

mybatis:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.patty.dubbo.provider.model
  type-handlers-package: com.patty.dubbo.provider.model
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    default-fetch-size: 100
    default-statement-timeout: 30

server:
  port: 8889